
import javax.swing.DefaultComboBoxModel;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author manuel
 */
public class main extends javax.swing.JFrame {

    /**
     * Creates new form main
     */
    public main() {
        initComponents();
        HiloHora h = new HiloHora(jl_hora);
        Thread proceso1 = new Thread(h);
        proceso1.start();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jd_administracion = new javax.swing.JDialog();
        btn_empleado = new javax.swing.JButton();
        btn_material = new javax.swing.JButton();
        btn_producto = new javax.swing.JButton();
        jl_opciones = new javax.swing.JLabel();
        jd_empleado = new javax.swing.JDialog();
        jTabbedPane1 = new javax.swing.JTabbedPane();
        jp_nuevo = new javax.swing.JPanel();
        btn_crearE = new javax.swing.JButton();
        jLabel2 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        tf_nombre = new javax.swing.JTextField();
        tf_id = new javax.swing.JTextField();
        sp_edad = new javax.swing.JSpinner();
        jScrollPane1 = new javax.swing.JScrollPane();
        ta_direccion = new javax.swing.JTextArea();
        sp_salario = new javax.swing.JSpinner();
        jp_editar = new javax.swing.JPanel();
        btn_modificarE = new javax.swing.JButton();
        sp_salario1 = new javax.swing.JSpinner();
        jScrollPane2 = new javax.swing.JScrollPane();
        ta_direccion1 = new javax.swing.JTextArea();
        sp_edad1 = new javax.swing.JSpinner();
        tf_id1 = new javax.swing.JTextField();
        tf_nombre1 = new javax.swing.JTextField();
        jLabel8 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();
        jLabel11 = new javax.swing.JLabel();
        jLabel12 = new javax.swing.JLabel();
        cb_empleado = new javax.swing.JComboBox();
        btn_seleccionarE = new javax.swing.JButton();
        jLabel22 = new javax.swing.JLabel();
        jp_eliminar = new javax.swing.JPanel();
        btn_eliminarE = new javax.swing.JButton();
        cb_empleados = new javax.swing.JComboBox();
        jLabel3 = new javax.swing.JLabel();
        btn_Mmenu3 = new javax.swing.JButton();
        jd_material = new javax.swing.JDialog();
        jTabbedPane2 = new javax.swing.JTabbedPane();
        jp_nuevo1 = new javax.swing.JPanel();
        btn_crearM = new javax.swing.JButton();
        jLabel13 = new javax.swing.JLabel();
        jLabel14 = new javax.swing.JLabel();
        jLabel15 = new javax.swing.JLabel();
        jLabel16 = new javax.swing.JLabel();
        tf_nombreM = new javax.swing.JTextField();
        tf_descripcionM = new javax.swing.JTextField();
        tf_marcaM = new javax.swing.JTextField();
        tf_serieM = new javax.swing.JTextField();
        jp_editar1 = new javax.swing.JPanel();
        btn_modificarM = new javax.swing.JButton();
        jLabel17 = new javax.swing.JLabel();
        tf_nombreM1 = new javax.swing.JTextField();
        jLabel35 = new javax.swing.JLabel();
        tf_descripcionM1 = new javax.swing.JTextField();
        jLabel36 = new javax.swing.JLabel();
        tf_marcaM1 = new javax.swing.JTextField();
        btn_seleccionarM = new javax.swing.JButton();
        cb_material = new javax.swing.JComboBox();
        jLabel29 = new javax.swing.JLabel();
        jp_eliminar1 = new javax.swing.JPanel();
        btn_eliminarM = new javax.swing.JButton();
        cb_materiales = new javax.swing.JComboBox();
        jLabel23 = new javax.swing.JLabel();
        btn_Mmenu2 = new javax.swing.JButton();
        jd_producto = new javax.swing.JDialog();
        jTabbedPane3 = new javax.swing.JTabbedPane();
        jp_nuevo2 = new javax.swing.JPanel();
        btn_crearP = new javax.swing.JButton();
        jLabel24 = new javax.swing.JLabel();
        jLabel25 = new javax.swing.JLabel();
        jLabel27 = new javax.swing.JLabel();
        jLabel28 = new javax.swing.JLabel();
        tf_nombre4 = new javax.swing.JTextField();
        tf_descripcion4 = new javax.swing.JTextField();
        cb_material2 = new javax.swing.JComboBox();
        btn_anadirM = new javax.swing.JButton();
        jScrollPane4 = new javax.swing.JScrollPane();
        table1 = new javax.swing.JTable();
        tf_tiempo4 = new javax.swing.JTextField();
        jp_editar2 = new javax.swing.JPanel();
        btn_modificarP = new javax.swing.JButton();
        jLabel26 = new javax.swing.JLabel();
        jLabel38 = new javax.swing.JLabel();
        jLabel39 = new javax.swing.JLabel();
        tf_nombre5 = new javax.swing.JTextField();
        tf_descripcion5 = new javax.swing.JTextField();
        jLabel30 = new javax.swing.JLabel();
        cb_producto = new javax.swing.JComboBox();
        btn_seleccionarP = new javax.swing.JButton();
        tf_tiempo5 = new javax.swing.JTextField();
        jLabel1 = new javax.swing.JLabel();
        cb_materialesPro = new javax.swing.JComboBox();
        btn_deleteMatP = new javax.swing.JButton();
        jLabel18 = new javax.swing.JLabel();
        cb_inventarioM = new javax.swing.JComboBox();
        btn_addMatPro = new javax.swing.JButton();
        jp_eliminar2 = new javax.swing.JPanel();
        btn_eliminarP = new javax.swing.JButton();
        cb_productos = new javax.swing.JComboBox();
        jLabel34 = new javax.swing.JLabel();
        btn_Mmenu1 = new javax.swing.JButton();
        jd_ensamblaje = new javax.swing.JDialog();
        jl_hora = new javax.swing.JLabel();
        cb_productosE = new javax.swing.JComboBox();
        btn_ensamblar = new javax.swing.JButton();
        jLabel19 = new javax.swing.JLabel();
        jLabel33 = new javax.swing.JLabel();
        btn_ensamblaje = new javax.swing.JButton();
        btn_administracion = new javax.swing.JButton();
        jLabel21 = new javax.swing.JLabel();
        jLabel31 = new javax.swing.JLabel();
        jLabel32 = new javax.swing.JLabel();
        jLabel20 = new javax.swing.JLabel();
        jMenuBar1 = new javax.swing.JMenuBar();

        btn_empleado.setText("Empleado");
        btn_empleado.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btn_empleadoMouseClicked(evt);
            }
        });

        btn_material.setText("Material");
        btn_material.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btn_materialMouseClicked(evt);
            }
        });

        btn_producto.setText("Producto");
        btn_producto.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btn_productoMouseClicked(evt);
            }
        });

        jl_opciones.setText("Elementos a Gestionar");

        javax.swing.GroupLayout jd_administracionLayout = new javax.swing.GroupLayout(jd_administracion.getContentPane());
        jd_administracion.getContentPane().setLayout(jd_administracionLayout);
        jd_administracionLayout.setHorizontalGroup(
            jd_administracionLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jd_administracionLayout.createSequentialGroup()
                .addGroup(jd_administracionLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jd_administracionLayout.createSequentialGroup()
                        .addGap(221, 221, 221)
                        .addComponent(jl_opciones, javax.swing.GroupLayout.PREFERRED_SIZE, 167, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jd_administracionLayout.createSequentialGroup()
                        .addGap(177, 177, 177)
                        .addGroup(jd_administracionLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(btn_empleado, javax.swing.GroupLayout.DEFAULT_SIZE, 244, Short.MAX_VALUE)
                            .addComponent(btn_material, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(btn_producto, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))))
                .addContainerGap(216, Short.MAX_VALUE))
        );
        jd_administracionLayout.setVerticalGroup(
            jd_administracionLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jd_administracionLayout.createSequentialGroup()
                .addGap(36, 36, 36)
                .addComponent(jl_opciones)
                .addGap(53, 53, 53)
                .addComponent(btn_empleado, javax.swing.GroupLayout.PREFERRED_SIZE, 74, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(52, 52, 52)
                .addComponent(btn_material, javax.swing.GroupLayout.DEFAULT_SIZE, 74, Short.MAX_VALUE)
                .addGap(42, 42, 42)
                .addComponent(btn_producto, javax.swing.GroupLayout.DEFAULT_SIZE, 74, Short.MAX_VALUE)
                .addGap(82, 82, 82))
        );

        jTabbedPane1.addChangeListener(new javax.swing.event.ChangeListener() {
            public void stateChanged(javax.swing.event.ChangeEvent evt) {
                jTabbedPane1StateChanged(evt);
            }
        });

        btn_crearE.setText("CREAR REGISTRO");
        btn_crearE.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btn_crearEMouseClicked(evt);
            }
        });

        jLabel2.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        jLabel2.setText("Nombre: ");

        jLabel4.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        jLabel4.setText("ID: ");

        jLabel5.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        jLabel5.setText("Edad: ");

        jLabel6.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        jLabel6.setText("Direccion: ");

        jLabel7.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        jLabel7.setText("Salario");

        sp_edad.setModel(new javax.swing.SpinnerNumberModel());

        ta_direccion.setColumns(20);
        ta_direccion.setRows(5);
        jScrollPane1.setViewportView(ta_direccion);

        sp_salario.setModel(new javax.swing.SpinnerNumberModel(Integer.valueOf(0), null, null, Integer.valueOf(1000)));

        javax.swing.GroupLayout jp_nuevoLayout = new javax.swing.GroupLayout(jp_nuevo);
        jp_nuevo.setLayout(jp_nuevoLayout);
        jp_nuevoLayout.setHorizontalGroup(
            jp_nuevoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jp_nuevoLayout.createSequentialGroup()
                .addGap(132, 132, 132)
                .addGroup(jp_nuevoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jp_nuevoLayout.createSequentialGroup()
                        .addGroup(jp_nuevoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel4)
                            .addComponent(jLabel5)
                            .addComponent(jLabel6)
                            .addComponent(jLabel7))
                        .addGroup(jp_nuevoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addGroup(jp_nuevoLayout.createSequentialGroup()
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addGroup(jp_nuevoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(sp_edad, javax.swing.GroupLayout.PREFERRED_SIZE, 58, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addGroup(jp_nuevoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                        .addComponent(tf_id, javax.swing.GroupLayout.PREFERRED_SIZE, 252, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addComponent(tf_nombre, javax.swing.GroupLayout.PREFERRED_SIZE, 252, javax.swing.GroupLayout.PREFERRED_SIZE))))
                            .addGroup(javax.swing.GroupLayout.Alignment.LEADING, jp_nuevoLayout.createSequentialGroup()
                                .addGap(117, 117, 117)
                                .addGroup(jp_nuevoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(jp_nuevoLayout.createSequentialGroup()
                                        .addComponent(sp_salario, javax.swing.GroupLayout.PREFERRED_SIZE, 129, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addGap(0, 0, Short.MAX_VALUE))
                                    .addComponent(jScrollPane1)))))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jp_nuevoLayout.createSequentialGroup()
                        .addComponent(jLabel2)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 124, Short.MAX_VALUE)
                        .addComponent(btn_crearE)
                        .addGap(117, 117, 117)))
                .addGap(228, 228, 228))
        );
        jp_nuevoLayout.setVerticalGroup(
            jp_nuevoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jp_nuevoLayout.createSequentialGroup()
                .addGap(44, 44, 44)
                .addGroup(jp_nuevoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2)
                    .addComponent(tf_nombre, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(17, 17, 17)
                .addGroup(jp_nuevoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel4)
                    .addComponent(tf_id, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jp_nuevoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel5)
                    .addComponent(sp_edad, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jp_nuevoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel6)
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 26, Short.MAX_VALUE)
                .addGroup(jp_nuevoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel7)
                    .addComponent(sp_salario, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(68, 68, 68)
                .addComponent(btn_crearE)
                .addGap(84, 84, 84))
        );

        jTabbedPane1.addTab("Nuevo", jp_nuevo);

        btn_modificarE.setText("MODIFICAR REGISTRO");
        btn_modificarE.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btn_modificarEMouseClicked(evt);
            }
        });

        sp_salario1.setModel(new javax.swing.SpinnerNumberModel(Integer.valueOf(0), null, null, Integer.valueOf(1000)));

        ta_direccion1.setColumns(20);
        ta_direccion1.setRows(5);
        jScrollPane2.setViewportView(ta_direccion1);

        sp_edad1.setModel(new javax.swing.SpinnerNumberModel());

        jLabel8.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        jLabel8.setText("Nombre: ");

        jLabel9.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        jLabel9.setText("ID: ");

        jLabel10.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        jLabel10.setText("Edad: ");

        jLabel11.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        jLabel11.setText("Direccion: ");

        jLabel12.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        jLabel12.setText("Salario");

        btn_seleccionarE.setText("Seleccionar");
        btn_seleccionarE.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btn_seleccionarEMouseClicked(evt);
            }
        });

        jLabel22.setFont(new java.awt.Font("Times New Roman", 0, 18)); // NOI18N
        jLabel22.setText("Empleado");

        javax.swing.GroupLayout jp_editarLayout = new javax.swing.GroupLayout(jp_editar);
        jp_editar.setLayout(jp_editarLayout);
        jp_editarLayout.setHorizontalGroup(
            jp_editarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jp_editarLayout.createSequentialGroup()
                .addGroup(jp_editarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jp_editarLayout.createSequentialGroup()
                        .addGap(331, 331, 331)
                        .addComponent(btn_modificarE))
                    .addGroup(jp_editarLayout.createSequentialGroup()
                        .addGap(224, 224, 224)
                        .addGroup(jp_editarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jp_editarLayout.createSequentialGroup()
                                .addGroup(jp_editarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLabel8)
                                    .addComponent(jLabel9)
                                    .addComponent(jLabel10)
                                    .addComponent(jLabel11)
                                    .addComponent(jLabel12))
                                .addGap(18, 18, 18)
                                .addGroup(jp_editarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(tf_nombre1, javax.swing.GroupLayout.PREFERRED_SIZE, 252, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jp_editarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                        .addComponent(tf_id1)
                                        .addComponent(sp_edad1, javax.swing.GroupLayout.PREFERRED_SIZE, 58, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 252, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addComponent(sp_salario1, javax.swing.GroupLayout.PREFERRED_SIZE, 129, javax.swing.GroupLayout.PREFERRED_SIZE))))
                            .addGroup(jp_editarLayout.createSequentialGroup()
                                .addComponent(jLabel22)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(cb_empleado, javax.swing.GroupLayout.PREFERRED_SIZE, 182, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(btn_seleccionarE)))))
                .addContainerGap(222, Short.MAX_VALUE))
        );
        jp_editarLayout.setVerticalGroup(
            jp_editarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jp_editarLayout.createSequentialGroup()
                .addGap(22, 22, 22)
                .addGroup(jp_editarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel22)
                    .addComponent(cb_empleado, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btn_seleccionarE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jp_editarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel8)
                    .addComponent(tf_nombre1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jp_editarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel9)
                    .addComponent(tf_id1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jp_editarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel10)
                    .addComponent(sp_edad1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jp_editarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel11)
                    .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 16, Short.MAX_VALUE)
                .addGroup(jp_editarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel12)
                    .addComponent(sp_salario1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(49, 49, 49)
                .addComponent(btn_modificarE)
                .addGap(87, 87, 87))
        );

        jTabbedPane1.addTab("Editar", jp_editar);

        btn_eliminarE.setText("Eliminar");
        btn_eliminarE.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btn_eliminarEMouseClicked(evt);
            }
        });

        javax.swing.GroupLayout jp_eliminarLayout = new javax.swing.GroupLayout(jp_eliminar);
        jp_eliminar.setLayout(jp_eliminarLayout);
        jp_eliminarLayout.setHorizontalGroup(
            jp_eliminarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jp_eliminarLayout.createSequentialGroup()
                .addGroup(jp_eliminarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jp_eliminarLayout.createSequentialGroup()
                        .addGap(295, 295, 295)
                        .addComponent(btn_eliminarE, javax.swing.GroupLayout.PREFERRED_SIZE, 183, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jp_eliminarLayout.createSequentialGroup()
                        .addGap(252, 252, 252)
                        .addComponent(cb_empleados, javax.swing.GroupLayout.PREFERRED_SIZE, 275, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(281, Short.MAX_VALUE))
        );
        jp_eliminarLayout.setVerticalGroup(
            jp_eliminarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jp_eliminarLayout.createSequentialGroup()
                .addContainerGap(107, Short.MAX_VALUE)
                .addComponent(cb_empleados, javax.swing.GroupLayout.PREFERRED_SIZE, 75, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(106, 106, 106)
                .addComponent(btn_eliminarE, javax.swing.GroupLayout.PREFERRED_SIZE, 48, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(147, 147, 147))
        );

        jTabbedPane1.addTab("Eliminar", jp_eliminar);

        jLabel3.setFont(new java.awt.Font("Sitka Text", 1, 24)); // NOI18N
        jLabel3.setText("EMPLEADO");

        btn_Mmenu3.setText("Main Menu");
        btn_Mmenu3.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btn_Mmenu3MouseClicked(evt);
            }
        });

        javax.swing.GroupLayout jd_empleadoLayout = new javax.swing.GroupLayout(jd_empleado.getContentPane());
        jd_empleado.getContentPane().setLayout(jd_empleadoLayout);
        jd_empleadoLayout.setHorizontalGroup(
            jd_empleadoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jd_empleadoLayout.createSequentialGroup()
                .addContainerGap(42, Short.MAX_VALUE)
                .addComponent(jTabbedPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 816, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(40, 40, 40))
            .addGroup(jd_empleadoLayout.createSequentialGroup()
                .addGap(372, 372, 372)
                .addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 150, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(btn_Mmenu3)
                .addGap(134, 134, 134))
        );
        jd_empleadoLayout.setVerticalGroup(
            jd_empleadoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jd_empleadoLayout.createSequentialGroup()
                .addGap(29, 29, 29)
                .addGroup(jd_empleadoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel3)
                    .addComponent(btn_Mmenu3))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jTabbedPane1)
                .addGap(19, 19, 19))
        );

        jTabbedPane2.addChangeListener(new javax.swing.event.ChangeListener() {
            public void stateChanged(javax.swing.event.ChangeEvent evt) {
                jTabbedPane2StateChanged(evt);
            }
        });

        btn_crearM.setText("CREAR REGISTRO");
        btn_crearM.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btn_crearMMouseClicked(evt);
            }
        });

        jLabel13.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        jLabel13.setText("Nombre: ");

        jLabel14.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        jLabel14.setText("Descripcion");

        jLabel15.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        jLabel15.setText("Marca");

        jLabel16.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        jLabel16.setText("Numero de Serie");

        javax.swing.GroupLayout jp_nuevo1Layout = new javax.swing.GroupLayout(jp_nuevo1);
        jp_nuevo1.setLayout(jp_nuevo1Layout);
        jp_nuevo1Layout.setHorizontalGroup(
            jp_nuevo1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jp_nuevo1Layout.createSequentialGroup()
                .addGroup(jp_nuevo1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jp_nuevo1Layout.createSequentialGroup()
                        .addGap(132, 132, 132)
                        .addGroup(jp_nuevo1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jp_nuevo1Layout.createSequentialGroup()
                                .addComponent(jLabel13)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(tf_nombreM, javax.swing.GroupLayout.PREFERRED_SIZE, 252, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(jp_nuevo1Layout.createSequentialGroup()
                                .addGroup(jp_nuevo1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLabel15)
                                    .addComponent(jLabel16))
                                .addGap(0, 0, Short.MAX_VALUE))
                            .addGroup(jp_nuevo1Layout.createSequentialGroup()
                                .addComponent(jLabel14)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(tf_descripcionM, javax.swing.GroupLayout.PREFERRED_SIZE, 252, javax.swing.GroupLayout.PREFERRED_SIZE))))
                    .addGroup(jp_nuevo1Layout.createSequentialGroup()
                        .addGap(331, 331, 331)
                        .addGroup(jp_nuevo1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(tf_serieM, javax.swing.GroupLayout.PREFERRED_SIZE, 252, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(tf_marcaM, javax.swing.GroupLayout.PREFERRED_SIZE, 252, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(btn_crearM, javax.swing.GroupLayout.PREFERRED_SIZE, 169, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(0, 0, Short.MAX_VALUE)))
                .addGap(228, 228, 228))
        );
        jp_nuevo1Layout.setVerticalGroup(
            jp_nuevo1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jp_nuevo1Layout.createSequentialGroup()
                .addGap(44, 44, 44)
                .addGroup(jp_nuevo1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel13)
                    .addComponent(tf_nombreM, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(40, 40, 40)
                .addGroup(jp_nuevo1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel14)
                    .addComponent(tf_descripcionM, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(44, 44, 44)
                .addGroup(jp_nuevo1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel15)
                    .addComponent(tf_marcaM, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(41, 41, 41)
                .addGroup(jp_nuevo1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel16)
                    .addComponent(tf_serieM, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 68, Short.MAX_VALUE)
                .addComponent(btn_crearM, javax.swing.GroupLayout.PREFERRED_SIZE, 44, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(87, 87, 87))
        );

        jTabbedPane2.addTab("Nuevo", jp_nuevo1);

        btn_modificarM.setText("MODIFICAR REGISTRO");
        btn_modificarM.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btn_modificarMMouseClicked(evt);
            }
        });

        jLabel17.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        jLabel17.setText("Nombre: ");

        jLabel35.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        jLabel35.setText("Descripcion");

        jLabel36.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        jLabel36.setText("Marca");

        btn_seleccionarM.setText("Seleccionar");
        btn_seleccionarM.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btn_seleccionarMMouseClicked(evt);
            }
        });

        jLabel29.setFont(new java.awt.Font("Times New Roman", 0, 18)); // NOI18N
        jLabel29.setText("Material");

        javax.swing.GroupLayout jp_editar1Layout = new javax.swing.GroupLayout(jp_editar1);
        jp_editar1.setLayout(jp_editar1Layout);
        jp_editar1Layout.setHorizontalGroup(
            jp_editar1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jp_editar1Layout.createSequentialGroup()
                .addGroup(jp_editar1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jp_editar1Layout.createSequentialGroup()
                        .addGap(168, 168, 168)
                        .addGroup(jp_editar1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel35)
                            .addComponent(jLabel17)
                            .addComponent(jLabel36))
                        .addGap(47, 47, 47)
                        .addGroup(jp_editar1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(tf_descripcionM1, javax.swing.GroupLayout.PREFERRED_SIZE, 252, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(tf_marcaM1, javax.swing.GroupLayout.PREFERRED_SIZE, 252, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(tf_nombreM1, javax.swing.GroupLayout.PREFERRED_SIZE, 252, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(jp_editar1Layout.createSequentialGroup()
                        .addGap(204, 204, 204)
                        .addComponent(jLabel29)
                        .addGap(18, 18, 18)
                        .addComponent(cb_material, javax.swing.GroupLayout.PREFERRED_SIZE, 182, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(btn_seleccionarM)))
                .addContainerGap(234, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jp_editar1Layout.createSequentialGroup()
                .addGap(0, 0, Short.MAX_VALUE)
                .addComponent(btn_modificarM, javax.swing.GroupLayout.PREFERRED_SIZE, 173, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(287, 287, 287))
        );
        jp_editar1Layout.setVerticalGroup(
            jp_editar1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jp_editar1Layout.createSequentialGroup()
                .addGap(46, 46, 46)
                .addGroup(jp_editar1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(cb_material, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btn_seleccionarM)
                    .addComponent(jLabel29))
                .addGap(49, 49, 49)
                .addGroup(jp_editar1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jLabel17)
                    .addComponent(tf_nombreM1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(47, 47, 47)
                .addGroup(jp_editar1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel35)
                    .addComponent(tf_descripcionM1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(38, 38, 38)
                .addGroup(jp_editar1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel36)
                    .addComponent(tf_marcaM1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(33, 33, 33)
                .addComponent(btn_modificarM, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(117, Short.MAX_VALUE))
        );

        jTabbedPane2.addTab("Editar", jp_editar1);

        btn_eliminarM.setText("Eliminar");
        btn_eliminarM.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btn_eliminarMMouseClicked(evt);
            }
        });

        javax.swing.GroupLayout jp_eliminar1Layout = new javax.swing.GroupLayout(jp_eliminar1);
        jp_eliminar1.setLayout(jp_eliminar1Layout);
        jp_eliminar1Layout.setHorizontalGroup(
            jp_eliminar1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jp_eliminar1Layout.createSequentialGroup()
                .addGap(295, 295, 295)
                .addGroup(jp_eliminar1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(btn_eliminarM, javax.swing.GroupLayout.DEFAULT_SIZE, 183, Short.MAX_VALUE)
                    .addComponent(cb_materiales, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap(330, Short.MAX_VALUE))
        );
        jp_eliminar1Layout.setVerticalGroup(
            jp_eliminar1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jp_eliminar1Layout.createSequentialGroup()
                .addContainerGap(115, Short.MAX_VALUE)
                .addComponent(cb_materiales, javax.swing.GroupLayout.PREFERRED_SIZE, 56, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(109, 109, 109)
                .addComponent(btn_eliminarM, javax.swing.GroupLayout.PREFERRED_SIZE, 48, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(152, 152, 152))
        );

        jTabbedPane2.addTab("Eliminar", jp_eliminar1);

        jLabel23.setFont(new java.awt.Font("Sitka Text", 1, 24)); // NOI18N
        jLabel23.setText("MATERIAL");

        btn_Mmenu2.setText("Main Menu");
        btn_Mmenu2.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btn_Mmenu2MouseClicked(evt);
            }
        });

        javax.swing.GroupLayout jd_materialLayout = new javax.swing.GroupLayout(jd_material.getContentPane());
        jd_material.getContentPane().setLayout(jd_materialLayout);
        jd_materialLayout.setHorizontalGroup(
            jd_materialLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jd_materialLayout.createSequentialGroup()
                .addContainerGap(43, Short.MAX_VALUE)
                .addComponent(jTabbedPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 816, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(40, 40, 40))
            .addGroup(jd_materialLayout.createSequentialGroup()
                .addGap(372, 372, 372)
                .addComponent(jLabel23, javax.swing.GroupLayout.PREFERRED_SIZE, 150, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(152, 152, 152)
                .addComponent(btn_Mmenu2)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jd_materialLayout.setVerticalGroup(
            jd_materialLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jd_materialLayout.createSequentialGroup()
                .addGap(29, 29, 29)
                .addGroup(jd_materialLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel23)
                    .addComponent(btn_Mmenu2))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jTabbedPane2)
                .addGap(19, 19, 19))
        );

        jTabbedPane3.addChangeListener(new javax.swing.event.ChangeListener() {
            public void stateChanged(javax.swing.event.ChangeEvent evt) {
                jTabbedPane3StateChanged(evt);
            }
        });

        btn_crearP.setText("CREAR REGISTRO");
        btn_crearP.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btn_crearPMouseClicked(evt);
            }
        });

        jLabel24.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        jLabel24.setText("Nombre: ");

        jLabel25.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        jLabel25.setText("Descripcion");

        jLabel27.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        jLabel27.setText("Tiempo:");

        jLabel28.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        jLabel28.setText("Materiales");

        btn_anadirM.setText("Añadir");
        btn_anadirM.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btn_anadirMMouseClicked(evt);
            }
        });

        table1.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Num. Serie", "Nombre"
            }
        ));
        jScrollPane4.setViewportView(table1);

        javax.swing.GroupLayout jp_nuevo2Layout = new javax.swing.GroupLayout(jp_nuevo2);
        jp_nuevo2.setLayout(jp_nuevo2Layout);
        jp_nuevo2Layout.setHorizontalGroup(
            jp_nuevo2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jp_nuevo2Layout.createSequentialGroup()
                .addGroup(jp_nuevo2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jp_nuevo2Layout.createSequentialGroup()
                        .addGroup(jp_nuevo2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addGroup(jp_nuevo2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                .addGroup(jp_nuevo2Layout.createSequentialGroup()
                                    .addGap(132, 132, 132)
                                    .addGroup(jp_nuevo2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                        .addComponent(jLabel25)
                                        .addComponent(jLabel27)
                                        .addComponent(jLabel24)))
                                .addGroup(jp_nuevo2Layout.createSequentialGroup()
                                    .addGap(58, 58, 58)
                                    .addComponent(jLabel28)
                                    .addGap(18, 18, 18)
                                    .addComponent(cb_material2, javax.swing.GroupLayout.PREFERRED_SIZE, 182, javax.swing.GroupLayout.PREFERRED_SIZE)))
                            .addGroup(javax.swing.GroupLayout.Alignment.LEADING, jp_nuevo2Layout.createSequentialGroup()
                                .addGap(216, 216, 216)
                                .addComponent(btn_anadirM)))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(jp_nuevo2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(tf_nombre4, javax.swing.GroupLayout.DEFAULT_SIZE, 252, Short.MAX_VALUE)
                            .addComponent(tf_descripcion4, javax.swing.GroupLayout.DEFAULT_SIZE, 252, Short.MAX_VALUE)
                            .addComponent(jScrollPane4, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 191, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(tf_tiempo4)))
                    .addGroup(jp_nuevo2Layout.createSequentialGroup()
                        .addGap(317, 317, 317)
                        .addComponent(btn_crearP)))
                .addContainerGap(214, Short.MAX_VALUE))
        );
        jp_nuevo2Layout.setVerticalGroup(
            jp_nuevo2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jp_nuevo2Layout.createSequentialGroup()
                .addGap(44, 44, 44)
                .addGroup(jp_nuevo2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel24)
                    .addComponent(tf_nombre4, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(17, 17, 17)
                .addGroup(jp_nuevo2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel25)
                    .addComponent(tf_descripcion4, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(32, 32, 32)
                .addGroup(jp_nuevo2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel27)
                    .addComponent(tf_tiempo4, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGroup(jp_nuevo2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jp_nuevo2Layout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addGroup(jp_nuevo2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel28)
                            .addComponent(cb_material2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(btn_anadirM)
                        .addGap(77, 77, 77))
                    .addGroup(jp_nuevo2Layout.createSequentialGroup()
                        .addGap(30, 30, 30)
                        .addComponent(jScrollPane4, javax.swing.GroupLayout.PREFERRED_SIZE, 121, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 64, Short.MAX_VALUE)))
                .addComponent(btn_crearP)
                .addGap(75, 75, 75))
        );

        jTabbedPane3.addTab("Nuevo", jp_nuevo2);

        btn_modificarP.setText("MODIFICAR REGISTRO");
        btn_modificarP.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btn_modificarPMouseClicked(evt);
            }
        });

        jLabel26.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        jLabel26.setText("Nombre: ");

        jLabel38.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        jLabel38.setText("Descripcion");

        jLabel39.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        jLabel39.setText("Tiempo:");

        jLabel30.setFont(new java.awt.Font("Times New Roman", 0, 18)); // NOI18N
        jLabel30.setText("Producto");

        btn_seleccionarP.setText("Seleccionar");
        btn_seleccionarP.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btn_seleccionarPMouseClicked(evt);
            }
        });

        jLabel1.setText("Materiales del Producto");

        btn_deleteMatP.setText("Eliminar");
        btn_deleteMatP.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btn_deleteMatPMouseClicked(evt);
            }
        });

        jLabel18.setText("Materiales de Catalogo");

        btn_addMatPro.setText("Agregar");
        btn_addMatPro.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btn_addMatProMouseClicked(evt);
            }
        });

        javax.swing.GroupLayout jp_editar2Layout = new javax.swing.GroupLayout(jp_editar2);
        jp_editar2.setLayout(jp_editar2Layout);
        jp_editar2Layout.setHorizontalGroup(
            jp_editar2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jp_editar2Layout.createSequentialGroup()
                .addGap(72, 72, 72)
                .addGroup(jp_editar2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jp_editar2Layout.createSequentialGroup()
                        .addGroup(jp_editar2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel38)
                            .addComponent(jLabel39))
                        .addGroup(jp_editar2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jp_editar2Layout.createSequentialGroup()
                                .addGroup(jp_editar2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jp_editar2Layout.createSequentialGroup()
                                        .addGap(0, 86, Short.MAX_VALUE)
                                        .addGroup(jp_editar2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addComponent(tf_nombre5, javax.swing.GroupLayout.PREFERRED_SIZE, 252, javax.swing.GroupLayout.PREFERRED_SIZE)
                                            .addComponent(tf_descripcion5, javax.swing.GroupLayout.PREFERRED_SIZE, 252, javax.swing.GroupLayout.PREFERRED_SIZE)))
                                    .addComponent(tf_tiempo5))
                                .addGap(309, 309, 309))
                            .addGroup(jp_editar2Layout.createSequentialGroup()
                                .addGap(31, 31, 31)
                                .addComponent(jLabel30)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(cb_producto, javax.swing.GroupLayout.PREFERRED_SIZE, 182, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(btn_seleccionarP)
                                .addGap(212, 212, 212))))
                    .addGroup(jp_editar2Layout.createSequentialGroup()
                        .addGroup(jp_editar2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel1)
                            .addComponent(btn_deleteMatP)
                            .addComponent(cb_materialesPro, javax.swing.GroupLayout.PREFERRED_SIZE, 157, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(155, 155, 155)
                        .addGroup(jp_editar2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(btn_addMatPro)
                            .addComponent(jLabel18)
                            .addComponent(cb_inventarioM, javax.swing.GroupLayout.PREFERRED_SIZE, 171, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(0, 0, Short.MAX_VALUE))))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jp_editar2Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(btn_modificarP)
                .addGap(323, 323, 323))
            .addGroup(jp_editar2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(jp_editar2Layout.createSequentialGroup()
                    .addGap(86, 86, 86)
                    .addComponent(jLabel26)
                    .addContainerGap(638, Short.MAX_VALUE)))
        );
        jp_editar2Layout.setVerticalGroup(
            jp_editar2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jp_editar2Layout.createSequentialGroup()
                .addGap(24, 24, 24)
                .addGroup(jp_editar2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel30)
                    .addComponent(cb_producto, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btn_seleccionarP))
                .addGap(18, 18, 18)
                .addComponent(tf_nombre5, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addGroup(jp_editar2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(tf_descripcion5, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel38))
                .addGap(35, 35, 35)
                .addGroup(jp_editar2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel39)
                    .addComponent(tf_tiempo5, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(32, 32, 32)
                .addGroup(jp_editar2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1)
                    .addComponent(jLabel18))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jp_editar2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(cb_materialesPro, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(cb_inventarioM, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGroup(jp_editar2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jp_editar2Layout.createSequentialGroup()
                        .addGap(18, 18, 18)
                        .addComponent(btn_deleteMatP))
                    .addGroup(jp_editar2Layout.createSequentialGroup()
                        .addGap(6, 6, 6)
                        .addComponent(btn_addMatPro)))
                .addGap(57, 57, 57)
                .addComponent(btn_modificarP)
                .addContainerGap(84, Short.MAX_VALUE))
            .addGroup(jp_editar2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(jp_editar2Layout.createSequentialGroup()
                    .addGap(65, 65, 65)
                    .addComponent(jLabel26)
                    .addContainerGap(392, Short.MAX_VALUE)))
        );

        jTabbedPane3.addTab("Editar", jp_editar2);

        btn_eliminarP.setText("Eliminar");
        btn_eliminarP.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btn_eliminarPMouseClicked(evt);
            }
        });

        javax.swing.GroupLayout jp_eliminar2Layout = new javax.swing.GroupLayout(jp_eliminar2);
        jp_eliminar2.setLayout(jp_eliminar2Layout);
        jp_eliminar2Layout.setHorizontalGroup(
            jp_eliminar2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jp_eliminar2Layout.createSequentialGroup()
                .addGroup(jp_eliminar2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jp_eliminar2Layout.createSequentialGroup()
                        .addGap(284, 284, 284)
                        .addComponent(btn_eliminarP, javax.swing.GroupLayout.PREFERRED_SIZE, 194, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jp_eliminar2Layout.createSequentialGroup()
                        .addGap(226, 226, 226)
                        .addComponent(cb_productos, javax.swing.GroupLayout.PREFERRED_SIZE, 298, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(287, Short.MAX_VALUE))
        );
        jp_eliminar2Layout.setVerticalGroup(
            jp_eliminar2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jp_eliminar2Layout.createSequentialGroup()
                .addGap(52, 52, 52)
                .addComponent(cb_productos, javax.swing.GroupLayout.PREFERRED_SIZE, 55, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(53, 53, 53)
                .addComponent(btn_eliminarP, javax.swing.GroupLayout.PREFERRED_SIZE, 48, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(278, Short.MAX_VALUE))
        );

        jTabbedPane3.addTab("Eliminar", jp_eliminar2);

        jLabel34.setFont(new java.awt.Font("Sitka Text", 1, 24)); // NOI18N
        jLabel34.setText("PRODUCTO");

        btn_Mmenu1.setText("Main Menu");
        btn_Mmenu1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btn_Mmenu1MouseClicked(evt);
            }
        });

        javax.swing.GroupLayout jd_productoLayout = new javax.swing.GroupLayout(jd_producto.getContentPane());
        jd_producto.getContentPane().setLayout(jd_productoLayout);
        jd_productoLayout.setHorizontalGroup(
            jd_productoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jd_productoLayout.createSequentialGroup()
                .addGap(372, 372, 372)
                .addComponent(jLabel34, javax.swing.GroupLayout.PREFERRED_SIZE, 150, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(btn_Mmenu1)
                .addGap(78, 78, 78))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jd_productoLayout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jTabbedPane3, javax.swing.GroupLayout.PREFERRED_SIZE, 816, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(20, 20, 20))
        );
        jd_productoLayout.setVerticalGroup(
            jd_productoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jd_productoLayout.createSequentialGroup()
                .addGap(29, 29, 29)
                .addGroup(jd_productoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel34)
                    .addComponent(btn_Mmenu1))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jTabbedPane3, javax.swing.GroupLayout.PREFERRED_SIZE, 516, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        jd_ensamblaje.setMaximumSize(new java.awt.Dimension(679, 502));
        jd_ensamblaje.setMinimumSize(new java.awt.Dimension(679, 502));
        jd_ensamblaje.setPreferredSize(new java.awt.Dimension(679, 502));
        jd_ensamblaje.setResizable(false);
        jd_ensamblaje.getContentPane().setLayout(null);

        jl_hora.setFont(new java.awt.Font("Times New Roman", 0, 18)); // NOI18N
        jl_hora.setForeground(new java.awt.Color(255, 255, 255));
        jl_hora.setText("jLabel22");
        jd_ensamblaje.getContentPane().add(jl_hora);
        jl_hora.setBounds(490, 13, 130, 22);

        cb_productosE.setBackground(new java.awt.Color(153, 0, 0));
        cb_productosE.setFont(new java.awt.Font("PMingLiU-ExtB", 0, 18)); // NOI18N
        jd_ensamblaje.getContentPane().add(cb_productosE);
        cb_productosE.setBounds(180, 240, 296, 29);

        btn_ensamblar.setBackground(new java.awt.Color(204, 0, 51));
        btn_ensamblar.setFont(new java.awt.Font("Yu Gothic", 0, 18)); // NOI18N
        btn_ensamblar.setText("ENSAMBLAR");
        btn_ensamblar.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btn_ensamblarMouseClicked(evt);
            }
        });
        jd_ensamblaje.getContentPane().add(btn_ensamblar);
        btn_ensamblar.setBounds(257, 339, 143, 39);

        jLabel19.setFont(new java.awt.Font("PMingLiU-ExtB", 0, 24)); // NOI18N
        jLabel19.setForeground(new java.awt.Color(255, 255, 255));
        jLabel19.setText("Escoger el producto que desea ensamblar:");
        jd_ensamblaje.getContentPane().add(jLabel19);
        jLabel19.setBounds(130, 140, 391, 30);

        jLabel33.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imgs/Red-Background-27.png"))); // NOI18N
        jLabel33.setText("jLabel33");
        jd_ensamblaje.getContentPane().add(jLabel33);
        jLabel33.setBounds(0, 0, 680, 510);

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setMaximumSize(new java.awt.Dimension(690, 490));
        setMinimumSize(new java.awt.Dimension(690, 490));
        setPreferredSize(new java.awt.Dimension(1040, 700));
        setResizable(false);
        getContentPane().setLayout(null);

        btn_ensamblaje.setBackground(new java.awt.Color(204, 0, 51));
        btn_ensamblaje.setFont(new java.awt.Font("Gloucester MT Extra Condensed", 0, 48)); // NOI18N
        btn_ensamblaje.setForeground(new java.awt.Color(102, 0, 51));
        btn_ensamblaje.setText("Ensamblaje");
        btn_ensamblaje.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btn_ensamblajeMouseClicked(evt);
            }
        });
        getContentPane().add(btn_ensamblaje);
        btn_ensamblaje.setBounds(380, 440, 400, 110);

        btn_administracion.setBackground(new java.awt.Color(204, 0, 51));
        btn_administracion.setFont(new java.awt.Font("Gloucester MT Extra Condensed", 0, 48)); // NOI18N
        btn_administracion.setForeground(new java.awt.Color(102, 0, 51));
        btn_administracion.setText("Administración");
        btn_administracion.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btn_administracionMouseClicked(evt);
            }
        });
        getContentPane().add(btn_administracion);
        btn_administracion.setBounds(380, 220, 400, 110);

        jLabel21.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imgs/red-glossy-orb_t (1).png"))); // NOI18N
        getContentPane().add(jLabel21);
        jLabel21.setBounds(150, 390, 210, 220);

        jLabel31.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imgs/red-glossy-orb_t (1).png"))); // NOI18N
        getContentPane().add(jLabel31);
        jLabel31.setBounds(150, 170, 210, 220);

        jLabel32.setFont(new java.awt.Font("Gloucester MT Extra Condensed", 0, 70)); // NOI18N
        jLabel32.setForeground(new java.awt.Color(255, 255, 255));
        jLabel32.setText("T  R  U  M  P      I  N  D  U  S  T  R  I  E  S");
        getContentPane().add(jLabel32);
        jLabel32.setBounds(130, 50, 840, 80);

        jLabel20.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imgs/525848.jpg"))); // NOI18N
        getContentPane().add(jLabel20);
        jLabel20.setBounds(0, 0, 1040, 690);
        setJMenuBar(jMenuBar1);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btn_empleadoMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btn_empleadoMouseClicked
        this.jd_administracion.setVisible(false);
        jd_empleado.setModal(true);
        jd_empleado.pack();
        jd_empleado.setLocationRelativeTo(this);
        jd_empleado.setVisible(true);
        DefaultComboBoxModel modelo = new DefaultComboBoxModel();
        cb_empleado.setModel(modelo);
        cb_empleados.setModel(modelo);
    }//GEN-LAST:event_btn_empleadoMouseClicked

    private void btn_materialMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btn_materialMouseClicked
        this.jd_administracion.setVisible(false);
        jd_material.setModal(true);
        jd_material.pack();
        jd_material.setLocationRelativeTo(this);
        jd_material.setVisible(true);
        DefaultComboBoxModel modelo = new DefaultComboBoxModel();
        cb_material.setModel(modelo);
        cb_materiales.setModel(modelo);
    }//GEN-LAST:event_btn_materialMouseClicked

    private void btn_productoMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btn_productoMouseClicked
        jd_producto.setModal(true);
        jd_producto.pack();
         DefaultComboBoxModel modelo = new DefaultComboBoxModel();

        for (int i = 0; i < catalogoMateriales.getSize(); i++) {
            modelo.addElement((Material) catalogoMateriales.get(i));
        }
        this.cb_material2.setModel(modelo);
        jd_producto.setLocationRelativeTo(this);
        jd_producto.setVisible(true);
    }//GEN-LAST:event_btn_productoMouseClicked

                           
    private void btn_crearEActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_crearEActionPerformed

    }//GEN-LAST:event_btn_crearEActionPerformed

    private void btn_administracionMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btn_administracionMouseClicked
        this.setVisible(false);
        this.jd_administracion.setModal(true);
        this.jd_administracion.pack();
        this.jd_administracion.setVisible(true);
    }//GEN-LAST:event_btn_administracionMouseClicked

    private void btn_crearMMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btn_crearMMouseClicked
        String nombre;
        String descripcion;
        String marca;
        String numSerie;
        boolean exist = false;
        nombre = this.tf_nombreM.getText();
        descripcion = this.tf_descripcionM.getText();
        marca = this.tf_marcaM.getText();
        numSerie = this.tf_serieM.getText();

        materialE = new Material(nombre, descripcion, marca, numSerie);

        if (catalogoMateriales.getSize() == 0) {
            catalogoMateriales.push(materialE);
            materiales.push(new Pila(materialE));
        } else {
            for (int i = 0; i < catalogoMateriales.getSize(); i++) {
                if (((Material) catalogoMateriales.get(i)).getNombre().toLowerCase().equals(materialE.getNombre().toLowerCase())
                        && ((Material) catalogoMateriales.get(i)).getMarca().toLowerCase().equals(materialE.getMarca().toLowerCase())) {
                    exist = true;
                    ((Pila) materiales.get(i)).push(materialE);
                }
            }

            if (exist == false) {
                materiales.push(new Pila(materialE));
                catalogoMateriales.push(materialE);
            }

        }

        this.tf_nombreM.setText("");
        this.tf_descripcionM.setText("");
        this.tf_marcaM.setText("");
        this.tf_serieM.setText("");
    }//GEN-LAST:event_btn_crearMMouseClicked


    private void jTabbedPane2StateChanged(javax.swing.event.ChangeEvent evt) {//GEN-FIRST:event_jTabbedPane2StateChanged
        DefaultComboBoxModel modelo = new DefaultComboBoxModel();

        for (int i = 0; i < catalogoMateriales.getSize(); i++) {
            modelo.addElement((Material) catalogoMateriales.get(i));
        }
        this.cb_material2.setModel(modelo);
        this.cb_materiales.setModel(modelo);
        this.cb_material.setModel(modelo);
    }//GEN-LAST:event_jTabbedPane2StateChanged

    private void btn_seleccionarMMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btn_seleccionarMMouseClicked
        materialE = (Material) this.cb_material.getSelectedItem();

        this.tf_nombreM1.setText(materialE.getNombre());
        this.tf_descripcionM1.setText(materialE.getDescripcion());
        this.tf_marcaM1.setText(materialE.getMarca());
    }//GEN-LAST:event_btn_seleccionarMMouseClicked

    private void btn_modificarMMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btn_modificarMMouseClicked
        String nombre;
        String descripcion;
        String marca;
        int posicion = catalogoMateriales.find(materialE);
        pilaTemporal = (Pila)materiales.get(posicion);
        
        nombre = this.tf_nombreM1.getText();
        descripcion = this.tf_descripcionM1.getText();
        marca = this.tf_marcaM1.getText();
        
        for (int i = 0; i < pilaTemporal.size; i++) {
            ((Material)pilaTemporal.pop()).setNombre(nombre);
            ((Material)pilaTemporal.pop()).setDescripcion(descripcion);
            ((Material)pilaTemporal.pop()).setMarca(marca);
        }
        
        materialE.setNombre(nombre);
        materialE.setDescripcion(descripcion);
        materialE.setMarca(marca);

        this.tf_nombreM1.setText("");
        this.tf_descripcionM1.setText("");
        this.tf_marcaM1.setText("");
        this.cb_material.setSelectedIndex(0);
    }//GEN-LAST:event_btn_modificarMMouseClicked

    private void btn_eliminarMMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btn_eliminarMMouseClicked
        materialE = (Material) this.cb_materiales.getSelectedItem();
        int posicion = catalogoMateriales.find(materialE);
        catalogoMateriales.remove(posicion);
        materiales.remove(posicion);
        
        DefaultComboBoxModel modelo = new DefaultComboBoxModel();

        for (int i = 0; i < catalogoMateriales.getSize(); i++) {
            modelo.addElement((Material) catalogoMateriales.get(i));
        }

        this.cb_materiales.setModel(modelo);
        this.cb_material.setModel(modelo);
        this.cb_materiales.setSelectedIndex(0);
    }//GEN-LAST:event_btn_eliminarMMouseClicked

    private void btn_crearEMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btn_crearEMouseClicked
        String nombre;
        String id;
        int edad;
        String direccion;
        double salario;
        
        nombre = tf_nombre.getText();
        id = tf_id.getText();
        edad = Integer.parseInt(sp_edad.getValue().toString());
        direccion = ta_direccion.getText();
        salario = Double.parseDouble(this.sp_salario.getValue().toString());
        
        empleadoE = new Empleado(nombre, id, edad,direccion,salario);
        
        empleados.push(empleadoE);
        
        tf_nombre.setText("");
        tf_id.setText("");
        sp_edad.setValue(0) ;
        ta_direccion.setText("");
        sp_salario.setValue(0);
    }//GEN-LAST:event_btn_crearEMouseClicked

    private void btn_modificarEMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btn_modificarEMouseClicked
        String nombre;
        String id;
        int edad;
        String direccion;
        double salario;
        
        nombre = tf_nombre1.getText();
        id = tf_id1.getText();
        edad = Integer.parseInt(sp_edad1.getValue().toString()) ;
        direccion = ta_direccion1.getText();
        salario = Double.parseDouble(sp_salario1.getValue().toString());
        
        empleadoE = (Empleado)this.cb_empleado.getSelectedItem();
        
        empleadoE.setNombre(nombre);
        empleadoE.setId(id);
        empleadoE.setEdad(edad);
        empleadoE.setDireccion(direccion);
        empleadoE.setSalario(salario);
        
        tf_nombre1.setText("");
        tf_id1.setText("");
        sp_edad1.setValue(0) ;
        ta_direccion1.setText("");
        sp_salario1.setValue(0);
        this.cb_empleado.setSelectedIndex(0);
    }//GEN-LAST:event_btn_modificarEMouseClicked

    private void btn_eliminarEMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btn_eliminarEMouseClicked
        empleadoE = (Empleado)cb_empleados.getSelectedItem();
        int j = empleados.find(empleadoE);
        empleados.remove(j);
        DefaultComboBoxModel modelo = new DefaultComboBoxModel();
        
        for(int i = 0; i < empleados.size; i++){
            modelo.addElement(((Empleado)empleados.get(i)));
        }
        
        this.cb_empleado.setModel(modelo);
        this.cb_empleados.setModel(modelo);
    }//GEN-LAST:event_btn_eliminarEMouseClicked

    private void jTabbedPane1StateChanged(javax.swing.event.ChangeEvent evt) {//GEN-FIRST:event_jTabbedPane1StateChanged
        DefaultComboBoxModel modelo = new DefaultComboBoxModel();
        
        for(int i = 0; i < empleados.size; i++){
            modelo.addElement(((Empleado)empleados.get(i)));
        }
        
        this.cb_empleado.setModel(modelo);
        this.cb_empleados.setModel(modelo);
    }//GEN-LAST:event_jTabbedPane1StateChanged

    private void jTabbedPane3StateChanged(javax.swing.event.ChangeEvent evt) {//GEN-FIRST:event_jTabbedPane3StateChanged
        DefaultComboBoxModel modelo = new DefaultComboBoxModel();
        DefaultComboBoxModel modelo2 = new DefaultComboBoxModel();
        
        for(int i = 0; i < productos.getSize(); i++){
            modelo2.addElement(productos.get(i));
        }
        
        for(int i = 0; i < catalogoMateriales.getSize(); i++){
            modelo.addElement((Material)catalogoMateriales.get(i));
        }
        
        this.cb_producto.setModel(modelo2);
        this.cb_productos.setModel(modelo2);
        this.cb_material2.setModel(modelo);
    }//GEN-LAST:event_jTabbedPane3StateChanged

    private void btn_anadirMMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btn_anadirMMouseClicked
      this.materialE = (Material)this.cb_material2.getSelectedItem();
      
      materialesProducto.push(materialE);
      
      modeloTabla = (DefaultTableModel)table1.getModel();
      String[] data = new String[2];
      data[0] = materialE.getNombre();
      data[1] = materialE.getMarca();
      modeloTabla.addRow(data);
      table1.setModel(modeloTabla);
    }//GEN-LAST:event_btn_anadirMMouseClicked

    private void btn_crearPMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btn_crearPMouseClicked
        String nombre;
        String descripcion;
        int tiempo;
        
        nombre = this.tf_nombre4.getText();
        descripcion = this.tf_descripcion4.getText();
        tiempo = Integer.parseInt(this.tf_tiempo4.getText());
        
        productoE = new Producto(nombre, descripcion, tiempo);
        productoE.setMateriales(materialesProducto);
        materialesProducto = new Lista();
        productos.push(productoE);
        
        this.tf_nombre4.setText("");
        this.tf_descripcion4.setText("");
        this.tf_tiempo4.setText("");
        
        DefaultTableModel modelo = (DefaultTableModel)table1.getModel();
        while(modelo.getRowCount()>0){
            modelo.removeRow(modelo.getRowCount()-1);
        }
        table1.setModel(modelo);
        modeloTabla = new DefaultTableModel();
    }//GEN-LAST:event_btn_crearPMouseClicked

    private void btn_Mmenu1MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btn_Mmenu1MouseClicked
        this.jd_producto.setVisible(false);
        this.pack();
        this.setVisible(true);
    }//GEN-LAST:event_btn_Mmenu1MouseClicked

    private void btn_Mmenu2MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btn_Mmenu2MouseClicked
        this.jd_material.setVisible(false);
        this.pack();
        this.setVisible(true);
    }//GEN-LAST:event_btn_Mmenu2MouseClicked

    private void btn_Mmenu3MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btn_Mmenu3MouseClicked
        this.jd_empleado.setVisible(false);
        this.pack();
        this.setVisible(true);
    }//GEN-LAST:event_btn_Mmenu3MouseClicked

    private void btn_seleccionarEMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btn_seleccionarEMouseClicked
        empleadoE = (Empleado) cb_empleado.getSelectedItem();

        tf_nombre1.setText(empleadoE.getNombre());
        tf_id1.setText(empleadoE.getId());
        sp_edad1.setValue(empleadoE.getEdad());
        ta_direccion1.setText(empleadoE.getDireccion());
        sp_salario1.setValue(empleadoE.getSalario());
    }//GEN-LAST:event_btn_seleccionarEMouseClicked

    private void btn_eliminarPMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btn_eliminarPMouseClicked
        productoE = (Producto)this.cb_productos.getSelectedItem();
        productos.remove(productos.find(productoE));
        DefaultComboBoxModel modelo = new DefaultComboBoxModel();
        
        for(int i = 0; i < productos.getSize(); i++){
            modelo.addElement(productos.get(i));
        }
        
        this.cb_productos.setModel(modelo);
    }//GEN-LAST:event_btn_eliminarPMouseClicked

    private void btn_seleccionarPMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btn_seleccionarPMouseClicked
        productoE = (Producto)this.cb_producto.getSelectedItem();
        
        this.tf_nombre5.setText(productoE.getNombre());
        this.tf_descripcion5.setText(productoE.getDescripcion());
        this.tf_tiempo5.setText(productoE.getTiempo()+"");
        
        DefaultComboBoxModel modelo = new DefaultComboBoxModel();
        for(int i = 0; i < productoE.getMateriales().getSize(); i++){
            modelo.addElement(productoE.getMateriales().get(i));
        }
        this.cb_materialesPro.setModel(modelo);
        
        DefaultComboBoxModel modelo2 = new DefaultComboBoxModel();
        for(int i = 0; i < catalogoMateriales.getSize(); i++){
            modelo2.addElement(catalogoMateriales.get(i));
        }
        this.cb_inventarioM.setModel(modelo2);
    }//GEN-LAST:event_btn_seleccionarPMouseClicked

    private void btn_deleteMatPMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btn_deleteMatPMouseClicked
        materialE = (Material)this.cb_materialesPro.getSelectedItem();
        productoE.getMateriales().remove(productoE.getMateriales().find(materialE));
        
        DefaultComboBoxModel modelo = new DefaultComboBoxModel();
        for(int i = 0; i < productoE.getMateriales().getSize(); i++){
            modelo.addElement(productoE.getMateriales().get(i));
        }
        this.cb_materialesPro.setModel(modelo);
        this.cb_materialesPro.setSelectedIndex(0);
    }//GEN-LAST:event_btn_deleteMatPMouseClicked

    private void btn_addMatProMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btn_addMatProMouseClicked
        materialE = (Material)this.cb_inventarioM.getSelectedItem();
        productoE.getMateriales().push(materialE);
        
        DefaultComboBoxModel modelo = new DefaultComboBoxModel();
        for(int i = 0; i < productoE.getMateriales().getSize(); i++){
            modelo.addElement(productoE.getMateriales().get(i));
        }
        this.cb_materialesPro.setModel(modelo);
        this.cb_inventarioM.setSelectedIndex(0);
    }//GEN-LAST:event_btn_addMatProMouseClicked

    private void btn_modificarPMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btn_modificarPMouseClicked
        productoE.setNombre(this.tf_nombre5.getText());
        productoE.setDescripcion(this.tf_descripcion5.getText());
        productoE.setTiempo(Integer.parseInt(this.tf_tiempo5.getText()));
        this.cb_producto.setSelectedIndex(0);
        this.tf_nombre5.setText("");
        this.tf_descripcion5.setText("");
        this.tf_tiempo5.setText("");
        DefaultComboBoxModel modelo2 = new DefaultComboBoxModel();
        this.cb_inventarioM.setModel(modelo2);
    }//GEN-LAST:event_btn_modificarPMouseClicked

    private void btn_ensamblajeMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btn_ensamblajeMouseClicked
        DefaultComboBoxModel modelo = new DefaultComboBoxModel();
        
        for(int i = 0; i < productos.getSize(); i++){
            modelo.addElement(productos.get(i));
        }
        
        this.cb_productosE.setModel(modelo);
    }//GEN-LAST:event_btn_ensamblajeMouseClicked

    private void btn_ensamblarMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btn_ensamblarMouseClicked
        // TODO add your handling code here:
    }//GEN-LAST:event_btn_ensamblarMouseClicked



    /**
     * @param args the command line arguments
     */

    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(main.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(main.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(main.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(main.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new main().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btn_Mmenu1;
    private javax.swing.JButton btn_Mmenu2;
    private javax.swing.JButton btn_Mmenu3;
    private javax.swing.JButton btn_addMatPro;
    private javax.swing.JButton btn_administracion;
    private javax.swing.JButton btn_anadirM;
    private javax.swing.JButton btn_crearE;
    private javax.swing.JButton btn_crearM;
    private javax.swing.JButton btn_crearP;
    private javax.swing.JButton btn_deleteMatP;
    private javax.swing.JButton btn_eliminarE;
    private javax.swing.JButton btn_eliminarM;
    private javax.swing.JButton btn_eliminarP;
    private javax.swing.JButton btn_empleado;
    private javax.swing.JButton btn_ensamblaje;
    private javax.swing.JButton btn_ensamblar;
    private javax.swing.JButton btn_material;
    private javax.swing.JButton btn_modificarE;
    private javax.swing.JButton btn_modificarM;
    private javax.swing.JButton btn_modificarP;
    private javax.swing.JButton btn_producto;
    private javax.swing.JButton btn_seleccionarE;
    private javax.swing.JButton btn_seleccionarM;
    private javax.swing.JButton btn_seleccionarP;
    private javax.swing.JComboBox cb_empleado;
    private javax.swing.JComboBox cb_empleados;
    private javax.swing.JComboBox cb_inventarioM;
    private javax.swing.JComboBox cb_material;
    private javax.swing.JComboBox cb_material2;
    private javax.swing.JComboBox cb_materiales;
    private javax.swing.JComboBox cb_materialesPro;
    private javax.swing.JComboBox cb_producto;
    private javax.swing.JComboBox cb_productos;
    private javax.swing.JComboBox cb_productosE;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel15;
    private javax.swing.JLabel jLabel16;
    private javax.swing.JLabel jLabel17;
    private javax.swing.JLabel jLabel18;
    private javax.swing.JLabel jLabel19;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel20;
    private javax.swing.JLabel jLabel21;
    private javax.swing.JLabel jLabel22;
    private javax.swing.JLabel jLabel23;
    private javax.swing.JLabel jLabel24;
    private javax.swing.JLabel jLabel25;
    private javax.swing.JLabel jLabel26;
    private javax.swing.JLabel jLabel27;
    private javax.swing.JLabel jLabel28;
    private javax.swing.JLabel jLabel29;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel30;
    private javax.swing.JLabel jLabel31;
    private javax.swing.JLabel jLabel32;
    private javax.swing.JLabel jLabel33;
    private javax.swing.JLabel jLabel34;
    private javax.swing.JLabel jLabel35;
    private javax.swing.JLabel jLabel36;
    private javax.swing.JLabel jLabel38;
    private javax.swing.JLabel jLabel39;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JMenuBar jMenuBar1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JScrollPane jScrollPane4;
    private javax.swing.JTabbedPane jTabbedPane1;
    private javax.swing.JTabbedPane jTabbedPane2;
    private javax.swing.JTabbedPane jTabbedPane3;
    private javax.swing.JDialog jd_administracion;
    private javax.swing.JDialog jd_empleado;
    private javax.swing.JDialog jd_ensamblaje;
    private javax.swing.JDialog jd_material;
    private javax.swing.JDialog jd_producto;
    private javax.swing.JLabel jl_hora;
    private javax.swing.JLabel jl_opciones;
    private javax.swing.JPanel jp_editar;
    private javax.swing.JPanel jp_editar1;
    private javax.swing.JPanel jp_editar2;
    private javax.swing.JPanel jp_eliminar;
    private javax.swing.JPanel jp_eliminar1;
    private javax.swing.JPanel jp_eliminar2;
    private javax.swing.JPanel jp_nuevo;
    private javax.swing.JPanel jp_nuevo1;
    private javax.swing.JPanel jp_nuevo2;
    private javax.swing.JSpinner sp_edad;
    private javax.swing.JSpinner sp_edad1;
    private javax.swing.JSpinner sp_salario;
    private javax.swing.JSpinner sp_salario1;
    private javax.swing.JTextArea ta_direccion;
    private javax.swing.JTextArea ta_direccion1;
    private javax.swing.JTable table1;
    private javax.swing.JTextField tf_descripcion4;
    private javax.swing.JTextField tf_descripcion5;
    private javax.swing.JTextField tf_descripcionM;
    private javax.swing.JTextField tf_descripcionM1;
    private javax.swing.JTextField tf_id;
    private javax.swing.JTextField tf_id1;
    private javax.swing.JTextField tf_marcaM;
    private javax.swing.JTextField tf_marcaM1;
    private javax.swing.JTextField tf_nombre;
    private javax.swing.JTextField tf_nombre1;
    private javax.swing.JTextField tf_nombre4;
    private javax.swing.JTextField tf_nombre5;
    private javax.swing.JTextField tf_nombreM;
    private javax.swing.JTextField tf_nombreM1;
    private javax.swing.JTextField tf_serieM;
    private javax.swing.JTextField tf_tiempo4;
    private javax.swing.JTextField tf_tiempo5;
    // End of variables declaration//GEN-END:variables

    Empleado empleadoE = new Empleado();
    Material materialE = new Material();
    Producto productoE = new Producto();
    Lista materiales = new Lista();
    Pila pilaTemporal = new Pila();
    Lista catalogoMateriales = new Lista();
    Lista materialesProducto = new Lista();
    Lista empleados = new Lista();
    Lista productos = new Lista();
    DefaultTableModel modeloTabla = new DefaultTableModel();
    

    /*
     Observaciones:
        -Deberiamos de cambiar el atributo tiempo como date con el formato de hrs mins segs
        -Hice la lista de materiales de productos con un text area pero necesito un j list para que se almacenen como objetos? podria ir almacenando en los materiales internamente pero no sabria como datarlo despues
        -Falta hacer las listas de cada uno, por eso todavia no se como recorrer los fors de cada combo box (Productos, Materiales, Empleados)
        -Quedan pendientes los metodos de eliminar, modificar, y crear. Igual todavia no se puede porque no estan las listas
        -Todavia falta el panel de ensamblaje
     */
}
